### ISSUE TITLE
Not working tinymce editor

### ISSUE THREAD

**Issue by vitalijm** [Hube2/acf-custom-field-locations-rule#4]
HI, sometimes working tinymce editors sometimes not, when disabling this plugin and creating some standart location rule, then text editors working as should be...

**Comment by vitalijm** [comment]
For know, some simple fix is using setTimeout function:

```
setTimeout(function(){
  $('.acf-field-select select').trigger('change');
  $('.acf-field-checkbox input').trigger('change');
  $('.acf-field-radio input').trigger('change');
  $('.acf-field-true-false input').trigger('change');
}, 5000);
```

Maybe some ideas how do this without timeout? Some window event?

**Comment by Hube2** [comment]
I look into this and do some testing, not sure why anything in this should interfere with tinymce.

**Comment by vitalijm** [comment]
Ok, thanks

**Comment by vitalijm** [comment]
Better changing to (With new custom additional "ready" event):
```
setTimeout(function(){
  $('.acf-field-select select').trigger('acf_location_ready');
  $('.acf-field-checkbox input').trigger('acf_location_ready');
  $('.acf-field-radio input').trigger('acf_location_ready');
  $('.acf-field-true-false input').trigger('acf_location_ready');
}, 5000);
```

**Comment by Hube2** [comment]
Sorry it's taken be so long to get back to this, I must have missed you're reply.

does your change mean that I should also alter the actions added at the top of the script from "ready" to "acf_location_ready". I seem to be missing something with about this action

**Comment by vitalijm** [comment]
acf_location_ready action can be renamed into something else, just not standart must be, like some 'ready'. Because when triggering standart action it can trigger other logic actions from other plugins. Currently I don't working with this plugin, so something new I cannot say :)

**Comment by Hube2** [comment]
See #3
